# Generated by Django 5.2.4 on 2026-06-11 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_cart_cartitem_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartItem',
            new_name='Cart_Item',
        ),
    ]
