# Generated by Django 5.2.4 on 2026-06-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0006_alter_cart_item_unique_together_order_orderitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='Order_Item',
        ),
    ]
